### PR TITLE
Fix: allow keep alive error to continue to the next device

### PR DESCRIPTION
**Pull request by rotem925**
Hi @deiger 
Please see the PR suggestion.
As I said, not really a python developer, so make any changes you like :)

This should solve the issue for #60 
The loop exception handling seems to skip the following devices.
I guessed that the queue_emty variable should have been inside the loop as well.

As I suggested in the #60 issue, I would set the MQTT device availability to off for HA.

### CODE REVIEW

**Comment by deiger** [comment]
The logic here is pushing messages to all ACs every _KEEP_ALIVE_INTERVAL (or less, if the condition is hit).
So the queues_empty is actually in the right place.
You're right that try-except logic should be inside the for loop, but that's the only change needed here.

**Comment by rotem925** [comment]
Hope I understood you correctly, can you please review it again?

**Comment by deiger** [comment]
That's better. Thanks.

**Comment by rotem925** [comment]
Superb! :)
Can you please have a look at the availability? A bit over my heas while I'm trying to understand the architecture..

**Comment by deiger** [comment]
Sure. I guess we need a separate one for each A/C.

**Comment by rotem925** [comment]
Yes indeed :)
I actually was able to achieve that, but I felt I mess too much with the code.. :/

**Pull request merged**
