### PR TITLE
Feature/cherry pick hass cleanup

### PR DESCRIPTION
**Pull request by karlkar**
Second part of preparing the script to easily integrate with Home Assistant

### CODE REVIEW

**Comment by deiger** [comment]
Hey, the pull request is full of restyling, that I'm not sure what is the source of (and makes finding the actual changes really challenging). I guess 79ece0f is to blame.
Why move from single quote to double quotes and 4 char indentation?
Can you please revert that?

**Comment by deiger** [comment]
Can you please fix this? Your previous pull request broke the code. I'd be happy to submit this one, assuming it fixes things, but please revert the totally unnecessary formatting "fix" in 79ece0f.

**Comment by deiger** [comment]
I've fixed the code, and added MQTT discovery support. Please resolve the conflicts and revert the formatting mess.

**Comment by karlkar** [comment]
Hey,
Most od comments related to the previous PR were about styling. I'm not a python guy, I don't really know all the conventions, so I've applied the same styling that is used in Home Assistant. I'm really sorry that you don't like it, you can change it whenever you want. I don't have time for that. 
Also sorry for not testing of the script was running in the "non-HA" way. I should have done it, but now again - don't have time for it. There's some more changes that I wanted to add in a separate PR. I'll add them today to this PR and you'll do whatever you want. 
Once again sorry.

**Comment by deiger** [comment]
No worries, thanks for the contribution.
The main issue with the reformatting (besides a matter of taste) is that it makes the diff utterly useless. I simple cannot tell what has changed, since "everything has".

**Comment by deiger** [comment]
I've applied code formatting using yapf (there is a config file in the root dir). If you ran it on your code, it should align most things, not the single/double quote changes though.

**Comment by wifi75** [comment]
@deiger how I can update to last version?

**Comment by deiger** [comment]
@wifi75  I suggest you wait with this PR until it is merged. For now just do a `git clone` from head.  Once it is merged you can do a `git pull` and run `python3.7 setup.py install` to update the installed module.

**Comment by wifi75** [comment]
I tryed to send git clone command on dir AirCon but command not work...can you explane step by step the command?

**Comment by deiger** [comment]
> I tryed to send git clone command on dir AirCon but command not work...can you explane step by step the command?

Sure:
```bash
$ git clone https://github.com/deiger/AirCon
$ cd AirCon
$ python3.7 setup.py install
$ python3.7 -m aircon discovery ...
```

* Note: for the setup you may need to add `sudo` for it to work.

**Comment by wifi75** [comment]
Thank you !!!

**Comment by deiger** [comment]
Hey @karlkar, would you like to push this PR forward? The code here is advancing onwards, with docker, MQTT discovery etc., and it may become harder to do the merge.

**Pull request closed without merging**
