### PR TITLE
Dockerfile support

### PR DESCRIPTION
**Pull request by rotem925**
Hi,
I've added support for Dockerfile.
Usefull for multiple ACs as well.

To build as docker image:
`docker build -t aircon:latest .`

To run the container
```
docker run \
-e USERNAME=example@example.com \
-e PASSWORD="1234"\
-e APP=tornado-us \
-e TYPE=ac \
-e LOG_LEVEL=WARNING \
-e MQTT_HOST=192.168.1.1\
-e MQTT_USER=username:pass \
-e PORT=8888 \
-v /opt/hisense:/opt/hisense \
--net host \
--name aircon -it aircon:latest
```
This will autorun the discovery for the specified app and type if there isn't any config file in the mounted folder.
Then will run the server with all the config files that were generated.
Also added another install requirement.. it seems like it does not run without _retry_ installed...
Will be glad to hear what you think.

### CODE REVIEW

**Comment by deiger** [comment]
Nice, thank you!
I think though I'd rather run the discovery once, rather than contact the servers on every restart.
That's the reason for maintaining config files.
How about mounting a local dir for the config files?

**Comment by rotem925** [comment]
I agree,
Can you create a dedicated folder for the configs files in the working directory?
That way I can just mount it into there and check if it is empty

**Comment by rotem925** [comment]
Or, I can just move it, what do you prefer?

**Comment by piejanssens** [comment]
https://hub.docker.com/ ? 😄

**Comment by rotem925** [comment]
Once we finalize some things, I think @deiger would be happy to push it 👍

**Comment by deiger** [comment]
Definitely! 😄 
@rotem925 Maybe `/opt/hisense`, similar to what I've seen in several other docker cases ( make it configurable of course).

**Comment by rotem925** [comment]
So to clarify, /opt/hisense will only hold the configs files, which means that I move the files right after the discovery.

**Comment by deiger** [comment]
Yes. Either that, or add a flag to the script to store it there in the first place.

**Comment by rotem925** [comment]
Ok, I've added the configuration volume, which will perform the discovery only when the configs do not exist.

**Comment by rotem925** [comment]
Currently, there are issues with docker. The device registration is failing with an error - just unable to connect. Don't really know the reason, but within docker it just does not work. 
Also tried it with network mode host and with a privileged flag for docker run.

This is related to issue #56.
The issues running inside at docker at the meoment are:
1. The discovery does not work for some ACs (can't fetch the MAC address)
2. The device registration phase (notifier.py) also does not work for every AC I have here.

If anyone has any insight on this, that would help.

**Comment by deiger** [comment]
For starters, let's use `--network host`, this should make things more straightforward.
Next, try running `arp` from the docker (enter it using `sudo docker exec -it aircon /bin/bash`).

**Comment by rotem925** [comment]
Ok,
arp was not installed, I've installed arp (apt-get install -y net-tools)
Now arp is resolved but same issue, this is the output from arp:
```
92.168.65.1             ether   f6:16:36:bc:f9:c6   C                     eth0
172.17.0.2               ether   02:42:ac:11:00:02   C                     docker0
```
using network mode host of course.

Here is the error log(part of it)
```

--- Logging error ---
Traceback (most recent call last):
  File "/app/aircon/notifier.py", line 85, in start
    await self._perform_request(session, entry)
  File "/usr/local/lib/python3.7/site-packages/tenacity-6.3.1-py3.7.egg/tenacity/_asyncio.py", line 79, in async_wrapped
    return await fn(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/tenacity-6.3.1-py3.7.egg/tenacity/_asyncio.py", line 42, in __call__
    do = self.iter(retry_state=retry_state)
  File "/usr/local/lib/python3.7/site-packages/tenacity-6.3.1-py3.7.egg/tenacity/__init__.py", line 360, in iter
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.7/site-packages/tenacity-6.3.1-py3.7.egg/tenacity/_asyncio.py", line 45, in __call__
    result = await fn(*args, **kwargs)
  File "/app/aircon/notifier.py", line 112, in _perform_request
    async with session.request(method, url, json=self._json, headers=config.headers) as resp:
  File "/usr/local/lib/python3.7/site-packages/aiohttp-3.6.2-py3.7-linux-x86_64.egg/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.7/site-packages/aiohttp-3.6.2-py3.7-linux-x86_64.egg/aiohttp/client.py", line 504, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.7/site-packages/aiohttp-3.6.2-py3.7-linux-x86_64.egg/aiohttp/client_reqrep.py", line 847, in start
    message, payload = await self._protocol.read()  # type: ignore  # noqa
  File "/usr/local/lib/python3.7/site-packages/aiohttp-3.6.2-py3.7-linux-x86_64.egg/aiohttp/streams.py", line 591, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/logging/handlers.py", line 934, in emit
    self.socket.send(msg)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/logging/handlers.py", line 855, in _connect_unixsocket
    self.socket.connect(address)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/logging/handlers.py", line 937, in emit
    self._connect_unixsocket(self.address)
  File "/usr/local/lib/python3.7/logging/handlers.py", line 866, in _connect_unixsocket
    self.socket.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
Call stack:
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/aircon/__main__.py", line 281, in <module>
    asyncio.run(run(parsed_args))
  File "/usr/local/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 574, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 541, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 1786, in _run_once
    handle._run()
  File "/usr/local/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/app/aircon/notifier.py", line 88, in start
    logging.exception('[KeepAlive] Failed to send local_reg keep alive to the AC.')
Message: '[KeepAlive] Failed to send local_reg keep alive to the AC.'
```

**Comment by deiger** [comment]
Try regenerating the config now that is on `network host`. Is it able to resolve the mac address?

**Comment by rotem925** [comment]
Tried it.. Same result.

**Comment by deiger** [comment]
If you ping the AC and then call `arp` within the container do you see it in the response?

**Comment by rotem925** [comment]
PIng does not work, also for the ACs that were resolved in the descovery.
That doesn't make any sense.
Tried also other computers I have on the network and I can't ping.

**Comment by deiger** [comment]
This is weird. `--network host` should really do the trick.
Try `docker inspect aircon`. Are you seeing `"NetworkMode": "host"` under `"HostConfig"`?

**Comment by deiger** [comment]
The resolve in discovery was done without accessing the LAN - it was based on the server's info.

**Comment by rotem925** [comment]
I can see it is in host mode.
This is not my first Dockerfile.. first time I see this thing.
What my first time is python.. Maybe this image has issues?

**Comment by rotem925** [comment]
Note on this, I've running on a mac, but I also tested it on my centos7

**Comment by rotem925** [comment]
Ok, found it, was a bit confusing... Same errors as before though..
I can ping now to all ACs - restarted the docker daemon..

**Comment by deiger** [comment]
I didn't doubt you've set it to network host, it's just debugging.
What was it?

**Comment by rotem925** [comment]
No worries :) didn't think you were doubting me. Just wanted you to understand that you SHOULD doubt me when it comes to python :) 

Something went wrong with docker daemon probably, just restarted the daemon and the ping started to work, including to the AC's that were failed during the discovery.

I still have all the errors in the log as posted before though.

**Comment by deiger** [comment]
OK, on to the next issue. Are the mac address in the config appearing after restart?

**Comment by rotem925** [comment]
After restarting the daemon?
No, still no config file created for those ACs

**Comment by deiger** [comment]
Is arp returning the MAC address for them after ping?

**Comment by rotem925** [comment]
After pinging, this is the output of arp -a:

`(192.168.65.1) at f6:16:36:bc:f9:c6 [ether] on eth0`

The ip I'm pinging is `192.168.1.253`
Note here, the docker subnet is: `192.168.65.0/24`

**Comment by rotem925** [comment]
We can try and share the cache of the arp and see what happens. But that won't be affected on macOS since it does not expose it to the file system. What do you think?

**Comment by rotem925** [comment]
Ok, I think we have some progress.
Seems to be an issue with macOS and docker..
Tried it on my centos7, just using the net host and it is picking all the ACs.
I see this in the error log after the discovery:
```

--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/logging/handlers.py", line 934, in emit
    self.socket.send(msg)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/logging/handlers.py", line 855, in _connect_unixsocket
    self.socket.connect(address)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/logging/handlers.py", line 937, in emit
    self._connect_unixsocket(self.address)
  File "/usr/local/lib/python3.7/logging/handlers.py", line 866, in _connect_unixsocket
    self.socket.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
Call stack:
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/aircon/__main__.py", line 281, in <module>
    asyncio.run(run(parsed_args))
  File "/usr/local/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 574, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 541, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 1786, in _run_once
    handle._run()
  File "/usr/local/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.7/site-packages/aiohttp-3.6.2-py3.7-linux-x86_64.egg/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/app/aircon/query_handlers.py", line 81, in property_update_handler
    logging.error('Unsupported update message = {}'.format(update['seq_no']))
Message: 'Unsupported update message = 345'
```

**Comment by deiger** [comment]
The error you got seems to be related to the logging. On linux the syslog handler is in /dev/log, in OS X it's /var/run/syslog, but neither exist on docker.
I think a better option is likely to enable journald in the code, and then make the docker use `"log-driver": "journald"`

**Comment by rotem925** [comment]
I can see the logs when looking into docker logs running `sudo docker logs aircon`

Not sure it is related to this error log though: `Message: "Failed to handle {'seq_no': 1114, 'data': {'name': 't_IBC', 'value': 144}}. Exception = 't_IBC'"`

**Comment by deiger** [comment]
The logging mechanism of HomeAssistant is journald:
```
            "LogConfig": {
                "Type": "journald",
                "Config": {}
            },
```

t_IBC isn't supported by your AC, don't worry about it.

**Comment by deiger** [comment]
Note that to use journald in Python we need to run `apt install python3-systemd`.

**Comment by rotem925** [comment]
Ok,
So is there anything you need me to adjust apart from adding python3-systemd package?

**Comment by rotem925** [comment]
Ok,
I saw you committed journaled support.
I've added the journaled driver to the docker run (also inspected it to make sure)
And the apt package.

I get these errors still (there some more errors I didn't include here):
```

--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/logging/handlers.py", line 934, in emit
    self.socket.send(msg)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/logging/handlers.py", line 855, in _connect_unixsocket
    self.socket.connect(address)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/logging/handlers.py", line 937, in emit
    self._connect_unixsocket(self.address)
  File "/usr/local/lib/python3.7/logging/handlers.py", line 866, in _connect_unixsocket
    self.socket.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
Call stack:
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/aircon/__main__.py", line 288, in <module>
    asyncio.run(run(parsed_args))
  File "/usr/local/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 574, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 541, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 1786, in _run_once
    handle._run()
  File "/usr/local/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.7/site-packages/aiohttp-3.6.2-py3.7-linux-x86_64.egg/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/app/aircon/query_handlers.py", line 81, in property_update_handler
    logging.error('Unsupported update message = {}'.format(update['seq_no']))
Message: 'Unsupported update message = 1104'
Arguments: ()

```

**Comment by deiger** [comment]
What? This doesn't seem like it's using the new handler.
Try entering python3 in the container, and run:
```
from systemd.journal import JournalHandler
logger = logging.getLogger('test')
logger.addHandler(JournalHandler())
logger.setLevel(logging.INFO)
logger.info("test 1,2,3")
```

**Comment by rotem925** [comment]
Here is the output, systemd is not recognized?

```
Python 3.7.9 (default, Dec 18 2020, 05:32:43)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from systemd.journal import JournalHandler
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'systemd'
>>> logger = logging.getLogger('test')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'logging' is not defined
>>> logger.addHandler(JournalHandler())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'logger' is not defined
>>> logger.setLevel(logging.INFO)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'logger' is not defined
>>> logger.info("test 1,2,3")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'logger' is not defined
```

**Comment by deiger** [comment]
How?? That's exactly what `apt install python3-systemd` does...

**Comment by rotem925** [comment]
I will guess that the docker image python:3.7 does not like the way I use apt to install it...
I tried with ubuntu image as well..
It installs it, but the command will run only if I do: `python3 -c 'from systemd.journal import JournalHandler'` (which uses python 3.6)
But running with python3.7: `python3.7 -c 'from systemd.journal import JournalHandler'` will fail that it does not find the module.

**Comment by rotem925** [comment]
I've just noticed this in the log while installing the package: `debconf: delaying package configuration, since apt-utils is not installed `
Happend right after installing the module:
```
Get:1 http://deb.debian.org/debian buster/main amd64 python3-systemd amd64 234-2+b1 [37.2 kB]
debconf: delaying package configuration, since apt-utils is not installed
```

**Comment by rotem925** [comment]
Forget it.. I think this warning leads to nothing as it does not suppose to harm..

**Comment by rotem925** [comment]
@deiger Maybe systemd is not something trivial on docker...
Should we maybe think of a different route? See this: https://medium.com/@yoanis_gil/logging-with-docker-part-1-b23ef1443aac

**Comment by rotem925** [comment]
Reading the error in the log more closely... are you sure it is related to the logging driver? It seems to me like it outputs the exception with all it's callstack

**Comment by rotem925** [comment]
hehe, I have something...
If you set use_stderr=True in the run process it works! (I can see the logs as we should) without any logging driver changes and not installing any package, see this on the __main__.py:

 ```
if parsed_args.cmd == 'run':
    setup_logger(parsed_args.log_level, use_stderr=True)
    asyncio.run(run(parsed_args))
  elif parsed_args.cmd == 'discovery':
    setup_logger(parsed_args.log_level, use_stderr=True)
    asyncio.run(discovery(parsed_args))
```

**Comment by deiger** [comment]
Hmm.. Yes, it seems just using `stderr` would really do the trick here (and then we don't need to install python3-systemd).
I tried changing the server code to do it on its own, but it turns out the only way to tell you're running in docker is by parsing `/proc/1/cgroup` (really ugly), or using a special ENV variable passed by the container script...

**Comment by rotem925** [comment]
I would use the ENV variable..
Another option would be to add an argument to the CLI.

**Comment by rotem925** [comment]
Damn it.. I think I've just locked my tornado account.. I get a 401 error now while signing it...
Maybe too many retries.. reset password did not work :/

**Comment by deiger** [comment]
OK, use PLATFORM=docker.
Yikes! Is it still locked?

**Comment by rotem925** [comment]
Unfortunately.. yes..
I will give it a shot tomorrow.
Ateast we have everything figured out :)

**Comment by rotem925** [comment]
@deiger I think tornado server has an issue. 
Just tried to create a new account and I can't.. Do you have their app? Can you confirm this?
Anyway, I've added the platform support and it works with my old configs, so I think you can merge it :)

Pushing it to docker hub would be awsome :)
Thanks

**Comment by rotem925** [comment]
@deiger Not sure it is related to here, but it seems like the status of all ACs in HA are on when it supposed to be off,
see the image below:

Screen Shot 2021-01-08 at 10 32 15

**Comment by deiger** [comment]
Sweet! I'll merge it. Thank you!
HA did not implement correctly the [power_command_topic](https://www.home-assistant.io/integrations/climate.mqtt/#power_command_topic) functionality. I already added a fix to turn on the AC if a different mode is selected, but I think there is some more work here.

**Comment by deiger** [comment]
Also added to hub.docker.com - use `docker pull deiger/aircon:latest`.

**Comment by deiger** [comment]
BTW, the server now supports controlling multiple ACs (by repeating the parameters), so the dockerfile needs to support this as well.

**Comment by rotem925** [comment]
> BTW, the server now supports controlling multiple ACs (by repeating the parameters), so the dockerfile needs to support this as well.

What do you mean? Didn't really understood what you mean by that..

**Comment by rotem925** [comment]
> @deiger Not sure it is related to here, but it seems like the status of all ACs in HA are on when it supposed to be off,
> see the image below:
> 
> Screen Shot 2021-01-08 at 10 32 15
> 
> I see more issues, I really think it is not related to Docker as I see it also when running manually.
> I have alot of entries in the logs:
> ```
> E0108 08:47:05.018  query_handlers.py:81] Unsupported update message = 3730
> E0108 08:47:05.059  query_handlers.py:81] Unsupported update message = 3032
> E0108 08:47:05.351  query_handlers.py:81] Unsupported update message = 3630
> E0108 08:47:06.196  query_handlers.py:81] Unsupported update message = 2868
> E0108 08:47:06.447  query_handlers.py:81] Unsupported update message = 3315
> E0108 08:47:06.893  query_handlers.py:81] Unsupported update message = 3731
> E0108 08:47:07.144  query_handlers.py:81] Unsupported update message = 3033
> E0108 08:47:07.311  query_handlers.py:81] Unsupported update message = 3631
> ```
> Also, when trying to control the AC (heat), it reverts the temperature from 25 to 23 which I can't see the reason...
> Maybe all related to the fact the AC seems on?
> 
> I use HA MQTT discovery, I guess that's the way right?
> I think off/on status is not affecting

@deiger can you also please help me on this one? It is not really usable at the moment as I can't control anything :/

**Comment by deiger** [comment]
> > BTW, the server now supports controlling multiple ACs (by repeating the parameters), so the dockerfile needs to support this as well.
> 
> What do you mean? Didn't really understood what you mean by that..
> It does repeat the parameters..

Ah, cool, missed that.

> > @deiger Not sure it is related to here, but it seems like the status of all ACs in HA are on when it supposed to be off,
> > see the image below:
> > Screen Shot 2021-01-08 at 10 32 15
> > I see more issues, I really think it is not related to Docker as I see it also when running manually.
> > I have alot of entries in the logs:
> > ```
> > E0108 08:47:05.018  query_handlers.py:81] Unsupported update message = 3730
> > E0108 08:47:05.059  query_handlers.py:81] Unsupported update message = 3032
> > E0108 08:47:05.351  query_handlers.py:81] Unsupported update message = 3630
> > E0108 08:47:06.196  query_handlers.py:81] Unsupported update message = 2868
> > E0108 08:47:06.447  query_handlers.py:81] Unsupported update message = 3315
> > E0108 08:47:06.893  query_handlers.py:81] Unsupported update message = 3731
> > E0108 08:47:07.144  query_handlers.py:81] Unsupported update message = 3033
> > E0108 08:47:07.311  query_handlers.py:81] Unsupported update message = 3631
> > ```
> > 
> > 
> > Also, when trying to control the AC (heat), it reverts the temperature from 25 to 23 which I can't see the reason...
> > Maybe all related to the fact the AC seems on?
> > I use HA MQTT discovery, I guess that's the way right?
> > I think off/on status is not affecting
> 
> @deiger can you also please help me on this one? It is not really usable at the moment as I can't control anything :/

I'll handle it. As you said, it's unrelated to the docker.

**Comment by rotem925** [comment]
Superb! Thanks!
Now I need full replacement to the tornado app, since they kicked me :)

**Comment by deiger** [comment]
Sure. I've never really used their app. I've disabled the AC's access to the internet shortly after configuring it (a year ago), as I don't trust their code not to open a back door into my network - even due to the fact that they never update the firmware... As the famous meme says, The S in IOT stands for Security.

**Comment by rotem925** [comment]
Everything local! That's the key.
I have another Tadiran AC here with tuya wifi module, still connected to the cloud, I wait for local tuya to support it..

Do you also have Tornado? How come the issues I have are different? Or maybe you do not use HA?

**Comment by deiger** [comment]
Yes, I also have Tornado. Up until a few weeks ago I was using SmartThings. It wasn't a trivial switch (and not really done yet).
Is the Tuya module ESP-based? You may be able to flash it with Tasmota, if you're up for it.

**Comment by deiger** [comment]
Do you think a `docker-compose` would be better than this long command-line?

**Comment by rotem925** [comment]
Not sure yet :)
I want to first handle all the Tornados ACs that I have here... I'll wait for you to fix the issues not abling to control them :) then move to Tuya :)
I have some Tasmota devices here(sonoff) It just works perfectly!
I don't mind using the local tuya, as it saves the flashing and works local anyway..

You did a smart move moving from SmartThings.. I moved from SmartThings a while ago, and the sky is the limit with HA.
Never thought I can control so many things that simple.
Just one thing which is still a pain with HA is Z-Wave. Migrated from several integrations which is pain.
I can recommend you read this if you interest, as it seems like the future for z-wave as a replacement to OpenZwave https://github.com/home-assistant/architecture/issues/483

**Comment by rotem925** [comment]
> Do you think a `docker-compose` would be better than this long command-line?

Actually, I use docker-compose, see this:
```

  tornadoac:
     image: deiger/aircon:latest
     container_name: tornadoac
     healthcheck:
       disable: true
     environment:
       - USERNAME=XXX
       - PASSWORD=XXX
       - APP=tornado-us
       - TYPE=ac
       - LOG_LEVEL=WARNING
       - MQTT_HOST=192.168.1.10
       - MQTT_USER=xxx:xxx
       - PORT=8888
     network_mode: host
     volumes:
       - ./tornadoac/config:/opt/hisense
      
```
I would also update the README.md
I think a lot are going to use it now with docker as it simplifies all the python thingy

**Comment by deiger** [comment]
Already fixed the issues, I believe.
Yes, my Z-Wave still goes through SmartThings - when there isn't a disconnect... I have a dongle on the way from the US.
I also need to buy a better Zigbee dongle, the miserable CC2531 isn't able to handle the load...

Right, I'm updating the README right now.

**Comment by rotem925** [comment]
Really? fixed it already? You just made my Shabat... Checking..

**Comment by rotem925** [comment]
And it works!!!!!
So freaking happy 👍  Thank you so much!
8 ACs down :) 1 to go :)

**Pull request merged**
